# 10. apply method 활용
- 사용자가 작성한 함수를 한 번에 데이터 프레임의 각 행과 열에 적용하여 실행할 수 있게 해주는 method
- 대용량 데이터 처리시, for문보다 빠름.

## 10.1. 간단한 함수 만들기

In [2]:
def my_sq(x):
    return x**2

def my_exp(x, n):
    return x**n

my_sq(4), my_exp(2, 4)

(16, 16)

## 10.2. apply method 사용하기 기초

In [3]:
import pandas as pd

df = pd.DataFrame({'a':[10,20,30], 'b':[20,30,40]})
df

    a   b
0  10  20
1  20  30
2  30  40

In [4]:
print(df['a']**2)
print(df['b']**2)

0    100
1    400
2    900
Name: a, dtype: int64
0     400
1     900
2    1600
Name: b, dtype: int64

In [5]:
sq = df['a'].apply(my_sq)
print(sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [6]:
ex = df['a'].apply(my_exp, n=2)
print(ex)

0    100
1    400
2    900
Name: a, dtype: int64

In [7]:
ex = df['a'].apply(my_exp, n=3)
print(ex)

0     1000
1     8000
2    27000
Name: a, dtype: int64

In [8]:
df = pd.DataFrame({'a':[10,20,30], 'b':[20,30,40]})
print(df)

    a   b
0  10  20
1  20  30
2  30  40

In [9]:
def print_me(x):
    print(x)

In [10]:
print(df.apply(print_me, axis=0)) # 함수를 데이터프레임의 열(0)단위로 적용할지, 행(1)단위로 적용할지 인자 설정

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64
a    None
b    None
dtype: object

In [23]:
# 열단위 출력 확인
print(df['a'])
print(df['b'])

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64

In [11]:
print(df.apply(print_me, axis=1)) # 행 단위

a    10
b    20
Name: 0, dtype: int64
a    20
b    30
Name: 1, dtype: int64
a    30
b    40
Name: 2, dtype: int64
0    None
1    None
2    None
dtype: object

In [12]:
# 행 단위 출력 확인
print(df.loc[0])
print(df.loc[1])

a    10
b    20
Name: 0, dtype: int64
a    20
b    30
Name: 1, dtype: int64

In [13]:
def avg_3(x, y, z):
    return (x+y+z)/3

In [14]:
# 오류 발생 - 3가지 인자를 전달하지 않음.
print(df.apply(avg_3))

TypeError: avg_3() missing 2 required positional arguments: 'y' and 'z'

In [24]:
# 열 단위 출력
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x+y+z)/3

print(df.apply(avg_3_apply))

a    20.0
b    30.0
dtype: float64

In [25]:
# 인자 개수를 모를 때

def avg_3_apply(col):
    sum = 0
    for item in col:
        sum += item

    return sum/df.shape[0] #

print(df.apply(avg_3_apply))

a    20.0
b    30.0
dtype: float64

In [26]:
# 행 단위 출력
def avg_2_apply(row):
    sum = 0
    for item in row:
        sum += item
    return sum/df.shape[1]

print(df.apply(avg_2_apply, axis=1)) # 행단위로 적용하기 위해 axis 설정

0    15.0
1    25.0
2    35.0
dtype: float64

## 10.3. apply method 사용하기 - 고급

In [27]:
import seaborn as sns

titanic = sns.load_dataset('titanic')

print(titanic.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
None

In [34]:
import numpy as np

def count_missing(vec):
    null_vec = pd.isnull(vec)
    null_count = np.sum(null_vec)
    return null_count

cmis_col = titanic.apply(count_missing)

print(pd.isnull(titanic).iloc[0:5, 0:5])
print('-'*50)
print(cmis_col)

   survived  pclass    sex    age  sibsp
0     False   False  False  False  False
1     False   False  False  False  False
2     False   False  False  False  False
3     False   False  False  False  False
4     False   False  False  False  False
--------------------------------------------------
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [37]:
def prop_missing(vec):
    num = count_missing(vec)
    dem = vec.size
    return num/dem

pmis_col = titanic.apply(prop_missing)
print(titanic.size)
print()
print(pmis_col)

13365

survived       0.000000
pclass         0.000000
sex            0.000000
age            0.198653
sibsp          0.000000
parch          0.000000
fare           0.000000
embarked       0.002245
class          0.000000
who            0.000000
adult_male     0.000000
deck           0.772166
embark_town    0.002245
alive          0.000000
alone          0.000000
dtype: float64

In [39]:
def prop_complete(vec):
    return 1 - prop_missing(vec)

pcom_col = titanic.apply(prop_complete)
print(pcom_col)

survived       1.000000
pclass         1.000000
sex            1.000000
age            0.801347
sibsp          1.000000
parch          1.000000
fare           1.000000
embarked       0.997755
class          1.000000
who            1.000000
adult_male     1.000000
deck           0.227834
embark_town    0.997755
alive          1.000000
alone          1.000000
dtype: float64

In [40]:
cmis_row = titanic.apply(count_missing, axis=1)
pmis_row = titanic.apply(prop_missing, axis=1)
pcom_row = titanic.apply(prop_complete, axis=1)

In [41]:
print(cmis_row.head())
print()
print(pmis_row.head())
print()
print(pcom_row.head())

0    1
1    0
2    1
3    0
4    1
dtype: int64

0    0.066667
1    0.000000
2    0.066667
3    0.000000
4    0.066667
dtype: float64

0    0.933333
1    1.000000
2    0.933333
3    1.000000
4    0.933333
dtype: float64

In [42]:
titanic['num_missing'] = titanic.apply(count_missing, axis=1)
print(titanic.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone  num_missing
0    man        True  NaN  Southampton    no  False            1
1  woman       False    C    Cherbourg   yes  False            0
2  woman       False  NaN  Southampton   yes   True            1
3  woman       False    C  Southampton   yes  False            0
4    man        True  NaN  Southampton    no   True            1

In [45]:
print(titanic.loc[titanic.num_missing > 1, :].sample(5))

     survived  pclass     sex  age  sibsp  parch     fare embarked   class  \
26          0       3    male  NaN      0      0   7.2250        C   Third
656         0       3    male  NaN      0      0   7.8958        S   Third
596         1       2  female  NaN      0      0  33.0000        S  Second
878         0       3    male  NaN      0      0   7.8958        S   Third
568         0       3    male  NaN      0      0   7.2292        C   Third

       who  adult_male deck  embark_town alive  alone  num_missing
26     man        True  NaN    Cherbourg    no   True            2
656    man        True  NaN  Southampton    no   True            2
596  woman       False  NaN  Southampton   yes   True            2
878    man        True  NaN  Southampton    no   True            2
568    man        True  NaN    Cherbourg    no   True            2