# 7. 깔끔한 데이터

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## 7.1. 열과 피벗

### 7.1.1. 넓은 데이터
- 여러 열들이 옆으로 길게 나열된 형태

In [ ]:
# melt method - 열 데이터를 행으로 정리

import pandas as pd
pew = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kuggle/data/data/pew.csv')
print(pew.head())

             religion  <$10k  $10-20k  $20-30k  $30-40k  $40-50k  $50-75k  \
0            Agnostic     27       34       60       81       76      137
1             Atheist     12       27       37       52       35       70
2            Buddhist     27       21       30       34       33       58
3            Catholic    418      617      732      670      638     1116
4  Don’t know/refused     15       14       15       11       10       35

   $75-100k  $100-150k  >150k  Don't know/refused
0       122        109     84                  96
1        73         59     74                  76
2        62         39     53                  54
3       949        792    633                1489
4        21         17     18                 116

In [ ]:
print(pew.iloc[:, 0:6])

                   religion  <$10k  $10-20k  $20-30k  $30-40k  $40-50k
0                  Agnostic     27       34       60       81       76
1                   Atheist     12       27       37       52       35
2                  Buddhist     27       21       30       34       33
3                  Catholic    418      617      732      670      638
4        Don’t know/refused     15       14       15       11       10
5          Evangelical Prot    575      869     1064      982      881
6                     Hindu      1        9        7        9       11
7   Historically Black Prot    228      244      236      238      197
8         Jehovah's Witness     20       27       24       24       21
9                    Jewish     19       19       25       25       30
10            Mainline Prot    289      495      619      655      651
11                   Mormon     29       40       48       51       56
12                   Muslim      6        7        9       10        9
13                 Orthodox     13       17       23       32       32
14          Other Christian      9        7       11       13       13
15             Other Faiths     20       33       40       46       49
16    Other World Religions      5        2        3        4        2
17             Unaffiliated    217      299      374      365      341

In [ ]:
# id_vars : 위치를 고정할 열 지정
pew_long = pd.melt(pew, id_vars='religion') # religion 열을 고정하여 피벗
print(pew_long.head())

             religion variable  value
0            Agnostic    <$10k     27
1             Atheist    <$10k     12
2            Buddhist    <$10k     27
3            Catholic    <$10k    418
4  Don’t know/refused    <$10k     15

In [ ]:
# var_name : 여러 열이 피벗되면서 묶이는 열 이름 지정
# value_name : 피벗되는 열의 값이 표현될 열 이름 지정
pew_long = pd.melt(pew, id_vars='religion',var_name='income', value_name='count')
print(pew_long.head())

             religion income  count
0            Agnostic  <$10k     27
1             Atheist  <$10k     12
2            Buddhist  <$10k     27
3            Catholic  <$10k    418
4  Don’t know/refused  <$10k     15

In [ ]:
billboard = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kuggle/data/data/billboard.csv')
print(billboard.iloc[0:5, 0:16])

   year        artist                    track  time date.entered  wk1   wk2  \
0  2000         2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   87  82.0
1  2000       2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   91  87.0
2  2000  3 Doors Down               Kryptonite  3:53   2000-04-08   81  70.0
3  2000  3 Doors Down                    Loser  4:24   2000-10-21   76  76.0
4  2000      504 Boyz            Wobble Wobble  3:35   2000-04-15   57  34.0

    wk3   wk4   wk5   wk6   wk7   wk8   wk9  wk10  wk11
0  72.0  77.0  87.0  94.0  99.0   NaN   NaN   NaN   NaN
1  92.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2  68.0  67.0  66.0  57.0  54.0  53.0  51.0  51.0  51.0
3  72.0  69.0  67.0  65.0  55.0  59.0  62.0  61.0  61.0
4  25.0  17.0  17.0  31.0  36.0  49.0  53.0  57.0  64.0

In [8]:
# 여러 열을 고정하는 경우
billboard_long = pd.melt(billboard, id_vars=['year', 'artist', 'track', 'time', 'date.entered'], var_name='week', value_name='rating')
print(billboard_long.head())

   year        artist                    track  time date.entered week  rating
0  2000         2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk1    87.0
1  2000       2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk1    91.0
2  2000  3 Doors Down               Kryptonite  3:53   2000-04-08  wk1    81.0
3  2000  3 Doors Down                    Loser  4:24   2000-10-21  wk1    76.0
4  2000      504 Boyz            Wobble Wobble  3:35   2000-04-15  wk1    57.0

## 7.2. 열이름 관리하기

### 7.2.1. 하나의 열에 여러 의미가 포함된 경우

In [9]:
ebola = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kuggle/data/data/country_timeseries.csv')
print(ebola.columns)

Index(['Date', 'Day', 'Cases_Guinea', 'Cases_Liberia', 'Cases_SierraLeone',
       'Cases_Nigeria', 'Cases_Senegal', 'Cases_UnitedStates', 'Cases_Spain',
       'Cases_Mali', 'Deaths_Guinea', 'Deaths_Liberia', 'Deaths_SierraLeone',
       'Deaths_Nigeria', 'Deaths_Senegal', 'Deaths_UnitedStates',
       'Deaths_Spain', 'Deaths_Mali'],
      dtype='object')

In [10]:
print(ebola.iloc[:5, [0, 1, 2, 3, 10, 11]])
# Guinea의 case/death와 Libera의 case/death가 모두 분리됨.

         Date  Day  Cases_Guinea  Cases_Liberia  Deaths_Guinea  Deaths_Liberia
0    1/5/2015  289        2776.0            NaN         1786.0             NaN
1    1/4/2015  288        2775.0            NaN         1781.0             NaN
2    1/3/2015  287        2769.0         8166.0         1767.0          3496.0
3    1/2/2015  286           NaN         8157.0            NaN          3496.0
4  12/31/2014  284        2730.0         8115.0         1739.0          3471.0

In [11]:
# Cases_Country, Deaths_coutry를 묶음.
ebola_long = pd.melt(ebola, id_vars=['Date', 'Day'])
print(ebola_long.head())

         Date  Day      variable   value
0    1/5/2015  289  Cases_Guinea  2776.0
1    1/4/2015  288  Cases_Guinea  2775.0
2    1/3/2015  287  Cases_Guinea  2769.0
3    1/2/2015  286  Cases_Guinea     NaN
4  12/31/2014  284  Cases_Guinea  2730.0

### 7.2.2. 하나의 열 분리하기

In [13]:
# split method : Splits the string in the Series/Index from the beginning, at the specified delimiter(regular expression) string.
variable_split = ebola_long.variable.str.split('_')

- __*accessor*__   
: 데이터 타입에 대해 고유한 작업이나 메서드를 제공하는 인터페이스  
ex) .str   
: attribute와 다름.   
:  속성처럼 '*.*' 연산자를 통해 접근할 수 있지만, 속성보다는 더 특수화된 작업을 위한 도구   
   
- __*attribute*__   
: Python 객체(object)에 저장된 값이나 속성, 상태를 나타내는 변수   
: 객체의 . 연산자를 통해 접근

In [14]:
print(type(variable_split))       # Series로 반환
print(type(variable_split[0]))    # 각 요소는 list로 반환

<class 'pandas.core.series.Series'>
<class 'list'>

In [15]:
# get 함수 : Extract element from lists, tuples, dict, or strings in each element in the Series/Index.
status_values = variable_split.str.get(0)   # 상태 부분 추출
country_values = variable_split.str.get(1)  # 나라 부분 추출

In [16]:
print(status_values[:5])
print()
print(status_values[-5:])

0    Cases
1    Cases
2    Cases
3    Cases
4    Cases
Name: variable, dtype: object

1947    Deaths
1948    Deaths
1949    Deaths
1950    Deaths
1951    Deaths
Name: variable, dtype: object

In [17]:
print(country_values[:5])
print()
print(country_values[-5:])

0    Guinea
1    Guinea
2    Guinea
3    Guinea
4    Guinea
Name: variable, dtype: object

1947    Mali
1948    Mali
1949    Mali
1950    Mali
1951    Mali
Name: variable, dtype: object

In [18]:
# 열 추가
ebola_long['status'] = status_values
ebola_long['country'] = country_values
print(ebola_long.head())

         Date  Day      variable   value status country
0    1/5/2015  289  Cases_Guinea  2776.0  Cases  Guinea
1    1/4/2015  288  Cases_Guinea  2775.0  Cases  Guinea
2    1/3/2015  287  Cases_Guinea  2769.0  Cases  Guinea
3    1/2/2015  286  Cases_Guinea     NaN  Cases  Guinea
4  12/31/2014  284  Cases_Guinea  2730.0  Cases  Guinea

In [ ]:
# 열 추가 방법 2
'''
variable_split = ebola_long.variable.str.split('_', expand=True)  # expand : bool, default False -  Expand the split strings into separate columns.
variable_split.columns = ['status', 'country']                    # columns 먼저 형성
ebola_parsed = pd.concat([ebola_long, variable_split], axis=1)    # axis : {0/'index', 1/'columns'}, default 0
'''

## 7.3. 여러 열을 하나로 정리하기

In [19]:
weather = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kuggle/data/data/weather.csv')
print(weather.iloc[:5, :])

        id  year  month element  d1    d2    d3  d4    d5  d6  ...  d22   d23  \
0  MX17004  2010      1    tmax NaN   NaN   NaN NaN   NaN NaN  ...  NaN   NaN
1  MX17004  2010      1    tmin NaN   NaN   NaN NaN   NaN NaN  ...  NaN   NaN
2  MX17004  2010      2    tmax NaN  27.3  24.1 NaN   NaN NaN  ...  NaN  29.9
3  MX17004  2010      2    tmin NaN  14.4  14.4 NaN   NaN NaN  ...  NaN  10.7
4  MX17004  2010      3    tmax NaN   NaN   NaN NaN  32.1 NaN  ...  NaN   NaN

   d24  d25  d26  d27  d28  d29   d30  d31
0  NaN  NaN  NaN  NaN  NaN  NaN  27.8  NaN
1  NaN  NaN  NaN  NaN  NaN  NaN  14.5  NaN
2  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN
3  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN
4  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN

[5 rows x 35 columns]

In [20]:
# 일별 온도 측정값(d1, d2, ..., d31)을 피벗
weather_melt = pd.melt(weather, id_vars=['id', 'year', 'month', 'element'], var_name='day', value_name='temp')
print(weather_melt.head())

        id  year  month element day  temp
0  MX17004  2010      1    tmax  d1   NaN
1  MX17004  2010      1    tmin  d1   NaN
2  MX17004  2010      2    tmax  d1   NaN
3  MX17004  2010      2    tmin  d1   NaN
4  MX17004  2010      3    tmax  d1   NaN

In [25]:
# pivot_table method : Create a spreadsheet-style pivot table as a DataFrame.
# (index=None, columns=None, aggfunc: AggFuncType='mean', dropna: bool=True,, observed: bool=False, sort: bool=True)
weather_tidy = weather_melt.pivot_table(
    index=['id', 'year', 'month', 'day'], #고정할 열
    columns='element',                    #피벗할 열
    values='temp',
    dropna=False
)
print(weather_tidy)
print(weather_tidy.columns)

element                 tmax  tmin
id      year month day
MX17004 2010 1     d1    NaN   NaN
                   d10   NaN   NaN
                   d11   NaN   NaN
                   d12   NaN   NaN
                   d13   NaN   NaN
...                      ...   ...
             12    d5    NaN   NaN
                   d6   27.8  10.5
                   d7    NaN   NaN
                   d8    NaN   NaN
                   d9    NaN   NaN

[341 rows x 2 columns]
Index(['tmax', 'tmin'], dtype='object', name='element')

In [24]:
# reset_index method : index를 새로 지정
weather_tidy_flat = weather_tidy.reset_index()
print(weather_tidy_flat.head())
print(weather_tidy_flat.shape)
# 원래 index를 풂. - column 수 증가

element       id  year  month  day  tmax  tmin
0        MX17004  2010      1   d1   NaN   NaN
1        MX17004  2010      1  d10   NaN   NaN
2        MX17004  2010      1  d11   NaN   NaN
3        MX17004  2010      1  d12   NaN   NaN
4        MX17004  2010      1  d13   NaN   NaN
(341, 6)

## 7.4. 중복 데이터 처리하기

In [26]:
billboard = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kuggle/data/data/billboard.csv')
billboard_long = pd.melt(billboard, id_vars=['year', 'artist', 'track', 'time', 'date.entered'], var_name='week', value_name='rating')

print(billboard_long.shape)
print()
print(billboard_long.head())

(24092, 7)

   year        artist                    track  time date.entered week  rating
0  2000         2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk1    87.0
1  2000       2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk1    91.0
2  2000  3 Doors Down               Kryptonite  3:53   2000-04-08  wk1    81.0
3  2000  3 Doors Down                    Loser  4:24   2000-10-21  wk1    76.0
4  2000      504 Boyz            Wobble Wobble  3:35   2000-04-15  wk1    57.0

In [27]:
# 중복데이터 확인 - year, artist, track, time, date 중복
print(billboard_long[billboard_long.track == 'Loser'].head())

      year        artist  track  time date.entered week  rating
3     2000  3 Doors Down  Loser  4:24   2000-10-21  wk1    76.0
320   2000  3 Doors Down  Loser  4:24   2000-10-21  wk2    76.0
637   2000  3 Doors Down  Loser  4:24   2000-10-21  wk3    72.0
954   2000  3 Doors Down  Loser  4:24   2000-10-21  wk4    69.0
1271  2000  3 Doors Down  Loser  4:24   2000-10-21  wk5    67.0

In [28]:
billboard_songs = billboard_long[['year', 'artist', 'track', 'time']]
print(billboard_songs.shape)

(24092, 4)

In [29]:
# drop_duplicates method : Return DataFrame with duplicate rows removed.
billboard_songs = billboard_songs.drop_duplicates()
print(billboard_songs.shape)

(317, 4)

In [30]:
# 노래 별로 index 지정
billboard_songs['id'] = range(len(billboard_songs)) # 순차적으로 index 지정
print(billboard_songs.head(n=10))

   year          artist                    track  time  id
0  2000           2 Pac  Baby Don't Cry (Keep...  4:22   0
1  2000         2Ge+her  The Hardest Part Of ...  3:15   1
2  2000    3 Doors Down               Kryptonite  3:53   2
3  2000    3 Doors Down                    Loser  4:24   3
4  2000        504 Boyz            Wobble Wobble  3:35   4
5  2000            98^0  Give Me Just One Nig...  3:24   5
6  2000         A*Teens            Dancing Queen  3:44   6
7  2000         Aaliyah            I Don't Wanna  4:15   7
8  2000         Aaliyah                Try Again  4:03   8
9  2000  Adams, Yolanda            Open My Heart  5:30   9

In [31]:
# merge method
# '주간 순위 데이터'와 '노래 정보 데이터' 합침. - 주간 순위 데이터에 노래별로 id 생성
billboard_ratings = billboard_long.merge(billboard_songs, on=['year', 'artist', 'track', 'time'])
print(billboard_ratings.shape)
print()
print(billboard_ratings.head())

(24092, 8)

   year artist                    track  time date.entered week  rating  id
0  2000  2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk1    87.0   0
1  2000  2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk2    82.0   0
2  2000  2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk3    72.0   0
3  2000  2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk4    77.0   0
4  2000  2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk5    87.0   0

## 7.5. 대용량 처리하기

### 7.5.1. 여러 개로 나누어진 데이터 불러오기

에러 발생

In [40]:
# import os
# import urllib.request



# # 여러 url이 담긴 text file 열기
# with open('/content/drive/MyDrive/Colab Notebooks/Kuggle/data/data/raw_data_urls.txt', 'r') as data_urls:
#     for line, url in enumerate(data_urls):     # enumerate → line = index / url = 해당 index 내용
#         if line == 5:                          # 다섯 번째 줄까지만 수행
#             break
#         fn = url.split('/')[-1].strip() # https://.../fhv_tripdata_2015-01.csv꼴 → 마지막 부분 추출 & '\n' 제거(file open시 항상 포함)
#         fp = os.path.join('', '/content/drive/MyDrive/Colab Notebooks/Kuggle/data/data', fn) # 파일 경로 설정
#         print(url)
#         print(fp)

#         # 지정된 URL에서 데이터를
#         headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'} #서버가 봇으로 인식할 수도 있으므로 header 첨가
#         request = urllib.request.Request(url, headers=headers)

#         try:
#           response = urllib.request.urlopen(request)

#             # 파일을 로컬 디렉토리에 저장
#           with open(fp, 'wb') as file:
#                 file.write(response.read())
#         except urllib.error.HTTPError as e:
#             print(f"Error downloading {url}: {e}")
#             # Handle the error appropriately, e.g., log it, skip to the next URL, etc.
#         '''
#         response = urllib.request.urlopen(request)

#         # 파일을 로컬 디렉토리에 저장
#         with open(fp, 'wb') as file:
#             file.write(response.read())
#         '''

https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-01.csv

/content/drive/MyDrive/Colab Notebooks/Kuggle/data/data/fhv_tripdata_2015-01.csv
Error downloading https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-01.csv
: HTTP Error 403: Forbidden
https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-02.csv

/content/drive/MyDrive/Colab Notebooks/Kuggle/data/data/fhv_tripdata_2015-02.csv
Error downloading https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-02.csv
: HTTP Error 403: Forbidden
https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-03.csv

/content/drive/MyDrive/Colab Notebooks/Kuggle/data/data/fhv_tripdata_2015-03.csv
Error downloading https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-03.csv
: HTTP Error 403: Forbidden
https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-04.csv

/content/drive/MyDrive/Colab Notebooks/Kuggle/data/data/fhv_tripdata_2015-04.csv
Error downloading https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-04.csv
: HTTP Error 403: Forbidden
https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-05.csv

/content/drive/MyDrive/Colab Notebooks/Kuggle/data/data/fhv_tripdata_2015-05.csv
Error downloading https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-05.csv
: HTTP Error 403: Forbidden

os.path.join을 사용할 때, 첫 번째 인자로 빈 문자열 ''을 전달하면 다음과 같은 상황에서 유용


1. 절대 경로로 시작할 때   
: os.path.join은 첫 번째 인자가 절대 경로라면, 이후의 모든 경로 조각들을 무시하고, 절대 경로로 시작하는 경로를 반환함. 이때 빈 문자열이 사용되면, 결합된 결과가 올바르게 작동하도록 도와줌.

2. 유연한 경로 결합   
: 빈 문자열을 첫 번째 인자로 넣으면, 경로 조합을 할 때 코드의 유연성을 높일 수 있음. 빈 문자열은 경로 결합에 영향을 미치지 않기 때문에, 조건에 따라 경로의 일부가 추가되거나 제거될 때 유용함.

In [41]:
# # vkdlf djqtdma.
# import glob
# nyc_taxi_data = glob.glob('/content/drive/MyDrive/Colab Notebooks/Kuggle/data/data/fhv_*')
# print(nyc_taxi_data)

[]

In [ ]:
'''
taxi1 = pd.read_csv(nyc_taxi_data[0])
taxi2 = pd.read_csv(nyc_taxi_data[1])
taxi3 = pd.read_csv(nyc_taxi_data[2])
taxi4 = pd.read_csv(nyc_taxi_data[3])
taxi5 = pd.read_csv(nyc_taxi_data[4])

print(taxi1.head(n=2))
print(taxi2.head(n=2))
print(taxi3.head(n=2))
print(taxi4.head(n=2))
print(taxi5.head(n=2))
'''

In [ ]:
# taxi = pd.concat([pd.read_csv(data) for data in nyc_taxi_data])
# #taxi = pd.concat([pd.read_csv(data) for data in nyc_taxi_data])
# print(taxi.shape)

In [ ]:
# list_taxi_df = []

# for csv_filename in nyc_taxi_data:
#     df = pd.read_csv(csv_filename)
#     list_taxi_df.append(df)      # dataframe을 요소로서 리스트 생성

# print(len(list_taxi_df))
# print(type(list_taxi_df[0]))

# taxi_loop_concat = pd.concat(list_taxi_df) # 리스트 내 모든 dataframe 결합
# print(taxi_loop_concat.shape)
# print(taxi.equals(taxi_loop_concat)) # True - 앞에서 얻은 taxi와 동일한지 확인